---
title: "BCRW predictions"
author: "Scott Forrest"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages}
#, warning=F, message=F

library(tidyverse)
packages <- c("lubridate", "terra", "dplyr", "sf", "beepr", "ctmm", "SpatialKDE", "tictoc", "ecospat", "raster", "patchwork")
walk(packages, require, character.only = T)

```


```{r}

# observed data
buffalo_CLR_year <- read_csv("outputs/buffalo_CLR_year_locations_20230220.csv")
attr(buffalo_CLR_year$t1, "tzone") <- "Australia/Queensland"
buffalo_CLR_year <- buffalo_CLR_year %>% mutate(hour = hour(t1))

# simulated data
sim_data <- read_csv("outputs/simulated trajectories/bcrw_buffalo_w_mean_loop_month1_100indvs_100ch_10000stps_2023-02-19.csv")

```

```{r}

# cropping extent
xmin <- 30000
xmax <- 32500
ymin <- -1436000
ymax <- -1433500
crop_extent <- ext(xmin, xmax, ymin, ymax)

## generating distribution map
# small extent
naive_predictions_cropped <- rast("outputs/simulated trajectories/prediction_maps/naive_predictions_cropped_20230222.tif")

```


```{r}

# ndvi_above0_stack_scaled <- rast("mapping/cropped rasters/ndvi_above0_stack_scaled_20230210.tif")
# slope_scaled <- rast("mapping/cropped rasters/slope_scaled_by_buffalo_data_20230210.tif")
# veg_herby <- rast("mapping/cropped rasters/veg_herby.tif")
# canopy_scaled <- rast("mapping/cropped rasters/canopy_scaled_by_buffalo_data_20230210.tif")
# 
# resource_stack <- c(ndvi_above0_stack_scaled[[1]],
#                     slope_scaled,
#                     veg_herby,
#                     canopy_scaled)
# 
# resources_cropped <- terra::crop(naive_predictions_cropped, crop_extent)
# resources_stack_cropped <- terra::crop(resource_stack, crop_extent)
# 
# ext(resources_stack_cropped) <- c(xmin - xmin,
#                             xmax - xmin,
#                             ymin - ymin,
#                             ymax - ymin)
# 
# terra::plot(resources_stack_cropped)

resources_cropped <- naive_predictions_cropped

points <- resources_cropped[[1]] #resource[[1]]
points[] <- 0
names(points) <- "bcrw"

sim_ud_points <- as.matrix(sim_data[,2:3])
counts <- as.data.frame(table(terra::cellFromXY(points, sim_ud_points))) # resources[[1]]
points[as.numeric(levels(counts$Var1))] <- counts$Freq

terra::plot(points)

# plot(points)
# points(x = sim_data$x, y = sim_data$y)  
terra::plot(resources_cropped[[1]])


naive_df <- as.data.frame(resources_cropped[[1]], xy = TRUE)

ggplot() +
  geom_raster(data = naive_df, aes(x = x, y = y, fill = naive_predictions)) +
  #geom_path(data = sim_data, aes(x = x_, y = y_, colour = id), size = 1) +
  # geom_point(data = sim_data, aes(x = x_, y = y_), size = 1, colour = "black", alpha = 0.05) + # colour = id
  geom_point(data = buffalo_CLR_year %>% filter(y == 1 & month == 1), aes(x = x1 - xmin, y = y1 - ymin), size = 1, colour = "red") +
  scale_fill_viridis_c() +
  scale_x_continuous(limits = c(0, xmax - xmin)) +
  scale_y_continuous(limits = c(0, ymax - ymin)) +
  # scale_colour_discrete(guide = FALSE) +
  #scale_fill_gradient(low = "white", high = "darkgreen") +
  coord_equal() +
  ggtitle("Naive Approach") +
  theme_bw()

```

```{r}

# terra::plot(rast(sim_data_kde))
# sim_data_kde_trim <- crop(rast(sim_data_kde), ext(resources_cropped))
# plot(sim_data_kde_trim)
# 
# # normalise to sum to 1
# sim_data_kde_trim_norm <- sim_data_kde_trim / global(sim_data_kde_trim, fun = "sum", na.rm = TRUE)[[1]]
# global(sim_data_kde_trim_norm, fun = "sum", na.rm = TRUE)
# 
# resources_cropped_norm <- resources_cropped / global(resources_cropped, fun = "sum", na.rm = TRUE)[[1]]
# global(resources_cropped_norm, fun = "sum", na.rm = TRUE)
# 
# points_norm <- points / global(points, fun = "sum", na.rm = TRUE)[[1]]
# global(points_norm, fun = "sum", na.rm = TRUE)[[1]]
# 
# plot(resources_cropped_norm)
# plot(points_norm)
# plot(sim_data_kde_trim_norm)

```


Importing data

```{r}

buffalo_CLR_year <- read_csv("outputs/buffalo_CLR_year_locations_20230220.csv")
attr(buffalo_CLR_year$t1, "tzone") <- "Australia/Queensland"

# buffalo data for checking predictions
buffalo_month1 <- buffalo_CLR_year %>% filter(y == 1 & month == 1)
buffalo_month1 <- buffalo_CLR_year %>% filter(y == 1 & month == 2)
buffalo_month1 <- buffalo_CLR_year %>% filter(y == 1 & month == 3)
buffalo_month1 <- buffalo_CLR_year %>% filter(y == 1 & month == 4)

# importing simulated data
sim_data_month1_1 <- read_csv("outputs/simulated trajectories/small_extent/bcrw_buffalo_w_mean_loop_month1_100indvs_100ch_10000stps_2023-02-19.csv")
sim_data_month1_2 <- read_csv("outputs/simulated trajectories/small_extent/bcrw_buffalo_w_mean_loop_month1_100indvs_100ch_10000stps_2023-02-22.csv")
sim_data_month1 <- rbind(sim_data_month1_1, sim_data_month1_2)
sim_data_month1$id <- rep(1:200, each = 1e4)

sim_data_month2 <- read_csv("outputs/simulated trajectories/bcrw_buffalo_w_mean_loop_month2_100indvs_100ch_10000stps_2023-02-23.csv")
sim_data_month3 <- read_csv("outputs/simulated trajectories/bcrw_buffalo_w_mean_loop_month3_100indvs_100ch_10000stps_2023-02-23.csv")
sim_data_month4 <- read_csv("outputs/simulated trajectories/bcrw_buffalo_w_mean_loop_month4_100indvs_100ch_10000stps_2023-02-23.csv")

sim_data <- sim_data_month1
sim_data <- sim_data_month2
sim_data <- sim_data_month3
sim_data <- sim_data_month4


month_n <- 1

template_raster <- naive_predictions_cropped[[month_n]]
template_raster_df <- as.data.frame(template_raster, xy = TRUE)

```


# Kernel density estimation with ks

```{r}

# cell_size <- 25
# band_width <- 10000

sim_data_matrix <- as.matrix(sim_data %>% dplyr::select(x_, y_))

# ks::Hpi(sim_data_matrix)
# ks::Hlscv(sim_data_matrix)
# ks::Hlscv.diag(sim_data_matrix)
# ks::Hnm(sim_data_matrix)
# H <- ks::Hnm.diag(sim_data_matrix)

tic()
kde_all_indvs <- ks::kde(x = sim_data_matrix,
                         eval.points = template_raster_df[,1:2]
                  # gridsize = rep(100,2),
                  # H = diag(c(band_width, band_width)),
                  # H = H
                  # xmin = -100,
                  # xmax = 200,
                  # binned = TRUE
                  )
toc()
# terra::plot(rast(kde_list_5indvs[[i]]$estimate))
# plot(kde_all_indvs, display = "image", col = viridis::viridis(20)) # doesn't work with eval.points as raster
# points(x = buffalo_month1$x1 - xmin, y = buffalo_month1$y1 - ymin)


total_indvs <- 200


#  1 individuals
n_indvs <- 1
kde_list_1indvs <- c()

for(i in 1:(total_indvs/n_indvs)) {

sim_data_matrix <- as.matrix(sim_data %>% filter(id %in% unique(sim_data$id)[((n_indvs*i)-(n_indvs-1)):(n_indvs*i)]) %>% dplyr::select(x_, y_)) 
tic() 
kde_list_1indvs[[i]] <- ks::kde(x = sim_data_matrix,
                                # H = diag(c(band_width, band_width))
                                ) 
toc()
plot(kde_list_1indvs[[i]], display = "image", col = viridis::viridis(20))

}


# 2 individuals
n_indvs <- 2
kde_list_2indvs <- c()

for(i in 1:(total_indvs/n_indvs)) {

sim_data_matrix <- as.matrix(sim_data %>% filter(id %in% unique(sim_data$id)[((n_indvs*i)-(n_indvs-1)):(n_indvs*i)]) %>% dplyr::select(x_, y_)) 
tic() 
kde_list_2indvs[[i]] <- ks::kde(x = sim_data_matrix,
                                # H = diag(c(band_width, band_width))
                                ) 
toc()
plot(kde_list_2indvs[[i]], display = "image", col = viridis::viridis(20))

}


# 5 individuals
n_indvs <- 5
kde_list_5indvs <- c()

for(i in 1:(total_indvs/n_indvs)) {

sim_data_matrix <- as.matrix(sim_data %>% filter(id %in% unique(sim_data$id)[((n_indvs*i)-(n_indvs-1)):(n_indvs*i)]) %>% dplyr::select(x_, y_)) 
tic() 
kde_list_5indvs[[i]] <- ks::kde(x = sim_data_matrix,
                                # H = diag(c(band_width, band_width))
                                ) 
toc()
plot(kde_list_5indvs[[i]], display = "image", col = viridis::viridis(20))

}


# 10 individuals
n_indvs <- 10
kde_list_10indvs <- c()

for(i in 1:(total_indvs/n_indvs)) {

sim_data_matrix <- as.matrix(sim_data %>% filter(id %in% unique(sim_data$id)[((n_indvs*i)-(n_indvs-1)):(n_indvs*i)]) %>% dplyr::select(x_, y_)) 
tic() 
kde_list_10indvs[[i]] <- ks::kde(x = sim_data_matrix,
                                # H = diag(c(band_width, band_width))
                                ) 
toc()
plot(kde_list_10indvs[[i]], display = "image", col = viridis::viridis(20))

}

# 20 individuals
n_indvs <- 20
kde_list_20indvs <- c()

for(i in 1:(total_indvs/n_indvs)) {

sim_data_matrix <- as.matrix(sim_data %>% filter(id %in% unique(sim_data$id)[((n_indvs*i)-(n_indvs-1)):(n_indvs*i)]) %>% dplyr::select(x_, y_)) 
tic() 
kde_list_20indvs[[i]] <- ks::kde(x = sim_data_matrix,
                                # H = diag(c(band_width, band_width))
                                ) 
toc()
plot(kde_list_20indvs[[i]], display = "image", col = viridis::viridis(20))

}

# 25 individuals
n_indvs <- 25
kde_list_25indvs <- c()

for(i in 1:(total_indvs/n_indvs)) {

sim_data_matrix <- as.matrix(sim_data %>% filter(id %in% unique(sim_data$id)[((n_indvs*i)-(n_indvs-1)):(n_indvs*i)]) %>% dplyr::select(x_, y_)) 
tic() 
kde_list_25indvs[[i]] <- ks::kde(x = sim_data_matrix,
                                # H = diag(c(band_width, band_width))
                                ) 
toc()
plot(kde_list_25indvs[[i]], display = "image", col = viridis::viridis(20))

}


# 50 individuals
n_indvs <- 50
kde_list_50indvs <- c()

for(i in 1:(total_indvs/n_indvs)) {

sim_data_matrix <- as.matrix(sim_data %>% filter(id %in% unique(sim_data$id)[((n_indvs*i)-(n_indvs-1)):(n_indvs*i)]) %>% dplyr::select(x_, y_)) 
tic() 
kde_list_50indvs[[i]] <- ks::kde(x = sim_data_matrix,
                                # H = diag(c(band_width, band_width))
                                ) 
toc()
plot(kde_list_50indvs[[i]], display = "image", col = viridis::viridis(20))

}


# 100 individuals
n_indvs <- 100
kde_list_50indvs <- c()

for(i in 1:(total_indvs/n_indvs)) {

sim_data_matrix <- as.matrix(sim_data %>% filter(id %in% unique(sim_data$id)[((n_indvs*i)-(n_indvs-1)):(n_indvs*i)]) %>% dplyr::select(x_, y_)) 
tic() 
kde_list_50indvs[[i]] <- ks::kde(x = sim_data_matrix,
                                # H = diag(c(band_width, band_width))
                                ) 
toc()
plot(kde_list_50indvs[[i]], display = "image", col = viridis::viridis(20))

}

```



```{r}

# kde_with_extent <- ks::kde(x = sim_data_matrix, eval.points = template_raster_df[,1:2])

#  1 individuals
n_indvs <- 1
kde_raster_list_1indvs <- vector(mode = "list", length = total_indvs/n_indvs)

for(i in 1:(total_indvs/n_indvs)) {
  tic()
  template_raster <- naive_predictions_cropped[[1]]

  sim_data_matrix <- as.matrix(sim_data %>% filter(id %in% unique(sim_data$id)[((n_indvs*i)-(n_indvs-1)):(n_indvs*i)]) %>%
                                 dplyr::select(x_, y_)) 

  # tic() 
    temp_obj <- ks::kde(x = sim_data_matrix,
                      eval.points = template_raster_df[,1:2]) 
  

  raster::values(template_raster) <- temp_obj$estimate
  raster::plot(template_raster)
  kde_raster_list_1indvs[[i]] <- raster::raster(template_raster)
  toc()
}


# 2 individuals
n_indvs <- 2
kde_raster_list_2indvs <- vector(mode = "list", length = total_indvs/n_indvs)

for(i in 1:(total_indvs/n_indvs)) {
  tic() 
  template_raster <- naive_predictions_cropped[[1]]

  sim_data_matrix <- as.matrix(sim_data %>% filter(id %in% unique(sim_data$id)[((n_indvs*i)-(n_indvs-1)):(n_indvs*i)]) %>%
                                 dplyr::select(x_, y_)) 

  
    temp_obj <- ks::kde(x = sim_data_matrix,
                      eval.points = template_raster_df[,1:2]) 
  

  raster::values(template_raster) <- temp_obj$estimate
  raster::plot(template_raster)
  kde_raster_list_2indvs[[i]] <- raster::raster(template_raster)
  toc()
}


# 5 individuals
n_indvs <- 5
kde_raster_list_5indvs <- vector(mode = "list", length = total_indvs/n_indvs)

for(i in 1:(total_indvs/n_indvs)) {
  
  template_raster <- naive_predictions_cropped[[1]]

  sim_data_matrix <- as.matrix(sim_data %>% filter(id %in% unique(sim_data$id)[((n_indvs*i)-(n_indvs-1)):(n_indvs*i)]) %>%
                                 dplyr::select(x_, y_)) 

  tic() 
    temp_obj <- ks::kde(x = sim_data_matrix,
                      eval.points = template_raster_df[,1:2]) 
  toc()

  raster::values(template_raster) <- temp_obj$estimate
  raster::plot(template_raster)
  kde_raster_list_5indvs[[i]] <- raster::raster(template_raster)

}


# 10 individuals
n_indvs <- 10
kde_raster_list_10indvs <- vector(mode = "list", length = total_indvs/n_indvs)

for(i in 1:(total_indvs/n_indvs)) {
  
  template_raster <- naive_predictions_cropped[[1]]

  sim_data_matrix <- as.matrix(sim_data %>% filter(id %in% unique(sim_data$id)[((n_indvs*i)-(n_indvs-1)):(n_indvs*i)]) %>%
                                 dplyr::select(x_, y_)) 

  tic() 
    temp_obj <- ks::kde(x = sim_data_matrix,
                      eval.points = template_raster_df[,1:2]) 
  toc()

  raster::values(template_raster) <- temp_obj$estimate
  raster::plot(template_raster)
  kde_raster_list_10indvs[[i]] <- raster::raster(template_raster)

}


# 20 individuals
n_indvs <- 20
kde_raster_list_20indvs <- vector(mode = "list", length = total_indvs/n_indvs)

for(i in 1:(total_indvs/n_indvs)) {
  
  template_raster <- naive_predictions_cropped[[1]]

  sim_data_matrix <- as.matrix(sim_data %>% filter(id %in% unique(sim_data$id)[((n_indvs*i)-(n_indvs-1)):(n_indvs*i)]) %>%
                                 dplyr::select(x_, y_)) 

  tic() 
    temp_obj <- ks::kde(x = sim_data_matrix,
                      eval.points = template_raster_df[,1:2]) 
  toc()

  raster::values(template_raster) <- temp_obj$estimate
  raster::plot(template_raster)
  kde_raster_list_20indvs[[i]] <- raster::raster(template_raster)

}


# 25 individuals
n_indvs <- 25
kde_raster_list_25indvs <- vector(mode = "list", length = total_indvs/n_indvs)

for(i in 1:(total_indvs/n_indvs)) {
  
  template_raster <- naive_predictions_cropped[[1]]

  sim_data_matrix <- as.matrix(sim_data %>% filter(id %in% unique(sim_data$id)[((n_indvs*i)-(n_indvs-1)):(n_indvs*i)]) %>%
                                 dplyr::select(x_, y_)) 

  tic() 
    temp_obj <- ks::kde(x = sim_data_matrix,
                      eval.points = template_raster_df[,1:2]) 
  toc()

  raster::values(template_raster) <- temp_obj$estimate
  raster::plot(template_raster)
  kde_raster_list_25indvs[[i]] <- raster::raster(template_raster)

}


# 50 individuals
n_indvs <- 50
kde_raster_list_50indvs <- vector(mode = "list", length = total_indvs/n_indvs)

for(i in 1:(total_indvs/n_indvs)) {
  
  template_raster <- naive_predictions_cropped[[1]]

  sim_data_matrix <- as.matrix(sim_data %>% filter(id %in% unique(sim_data$id)[((n_indvs*i)-(n_indvs-1)):(n_indvs*i)]) %>%
                                 dplyr::select(x_, y_)) 

  tic() 
    temp_obj <- ks::kde(x = sim_data_matrix,
                      eval.points = template_raster_df[,1:2]) 
  toc()

  raster::values(template_raster) <- temp_obj$estimate
  raster::plot(template_raster)
  kde_raster_list_50indvs[[i]] <- raster::raster(template_raster)

}


# 100 individuals
n_indvs <- 100
kde_raster_list_100indvs <- vector(mode = "list", length = total_indvs/n_indvs)

for(i in 1:(total_indvs/n_indvs)) {
  
  template_raster <- naive_predictions_cropped[[1]]

  sim_data_matrix <- as.matrix(sim_data %>% filter(id %in% unique(sim_data$id)[((n_indvs*i)-(n_indvs-1)):(n_indvs*i)]) %>%
                                 dplyr::select(x_, y_)) 

  tic() 
    temp_obj <- ks::kde(x = sim_data_matrix,
                      eval.points = template_raster_df[,1:2]) 
  toc()

  raster::values(template_raster) <- temp_obj$estimate
  raster::plot(template_raster)
  kde_raster_list_100indvs[[i]] <- raster::raster(template_raster)

}

```



```{r}

# beep(sound = 2)

template_raster <- naive_predictions_cropped[[month_n]]
names(template_raster) <- "sim_predictions"
template_raster_df <- as.data.frame(template_raster, xy = TRUE)

kde_with_extent <- ks::kde(x = sim_data_matrix, eval.points = template_raster_df[,1:2])
# plot(kde_with_extent, display = "image", col = viridis::viridis(20))

# for ggplot
kde_df <- data.frame(kde_with_extent$eval.points, "kde_estimate" = kde_with_extent$estimate)

# template_raster <- terra::setValues(template_raster, kde_all_indvs$estimate)
# template_raster <- kde_all_indvs
# 
# terra::plot(rast(sim_data_kde))
# sim_data_kde_trim <- crop(rast(sim_data_kde), ext(resources_cropped))
# plot(sim_data_kde_trim)

# normalise to sum to 1
# sim_data_kde_trim_norm <- sim_data_kde_trim / global(sim_data_kde_trim, fun = "sum", na.rm = TRUE)[[1]]
# global(sim_data_kde_trim_norm, fun = "sum", na.rm = TRUE)
# 
# resources_cropped_norm <- resources_cropped / global(resources_cropped, fun = "sum", na.rm = TRUE)[[1]]
# global(resources_cropped_norm, fun = "sum", na.rm = TRUE)
# 
# points_norm <- points / global(points, fun = "sum", na.rm = TRUE)[[1]]
# global(points_norm, fun = "sum", na.rm = TRUE)[[1]]
# 
# plot(resources_cropped_norm)
# plot(points_norm)
# plot(sim_data_kde_trim_norm)

```


# Loop over KDE

over the months

```{r}

cell_size <- 25
band_width <- 50

sim_data_kde_list <- vector(mode = "list", length = 12)

bcrw_sims <- list.files(paste0("outputs/simulated trajectories"))

bcrw_list <- vector(mode = "list", length = length(bcrw_sims))

for(i in 1:6){
  bcrw_list[[i]] <-  read_csv(paste0("outputs/simulated trajectories/",
                                             bcrw_sims[[i]]))
}

```



```{r}

# sim_data_kde_trim <- crop(rast(sim_data_kde), ext(resources_cropped))
# # normalise to sum to 1
# sim_data_kde_trim_norm <- sim_data_kde_trim / global(sim_data_kde_trim, fun = "sum", na.rm = TRUE)[[1]]

```



```{r}

# ext(resources_cropped_norm) <- ext(30000, 32000, -1436000, -1434000)
# ext(points_norm) <- ext(30000, 32000, -1436000, -1434000)
# ext(sim_data_kde_trim_norm) <- ext(30000, 32000, -1436000, -1434000)
# 
# names(naive_predictions_cropped) <- c("naive_predictions1", "naive_predictions2", "naive_predictions3", "naive_predictions4", "naive_predictions5", "naive_predictions6", "naive_predictions7", "naive_predictions8", "naive_predictions9", "naive_predictions10", "naive_predictions11", "naive_predictions12")

# naive_cropped_df <- as.data.frame(resources_cropped_norm, xy = TRUE)
naive_predictions_cropped_df <- as.data.frame(naive_predictions_cropped[[month_n]], xy = TRUE)
# month(with_tz(time(naive_predictions_cropped), tzone = "Australia/Queensland"))

# points_df <- as.data.frame(points_norm, xy = TRUE)
points_df <- as.data.frame(points, xy = TRUE)
# sim_data_kde_df <- as.data.frame(sim_data_kde_trim_norm, xy = TRUE)

naive_cropped_df
points_df
sim_data_kde_df

### NAIVE ###

naive_pred <- ggplot() +
  geom_raster(data = naive_predictions_cropped_df, aes(x = x, y = y, fill = naive_predictions)) +
  geom_point(data = buffalo_CLR_year %>% filter(y == 1 & month == 1), #  & hour %in% 12:17
             aes(x = x1 - xmin, y = y1 - ymin),  
             size = 0.5, 
             colour = "red", alpha = 0.25) +
  coord_equal() +
  scale_x_continuous(limits = c(0, xmax - xmin)) +
  scale_y_continuous(limits = c(0, ymax - ymin)) +
  # scale_x_continuous(limits = c(30000, 32000)) +
  # scale_y_continuous(limits = c(-1436000, -1434000)) +
  scale_fill_viridis_c("Naive", option = "D") +
  theme_classic() +
  theme(legend.position = "bottom", legend.key.width = unit(1, "cm"))

# ggsave("outputs/plots/bcrw_simulations/naive_cropped_wpoints_20230217png", width=150, height=90, units="mm", dpi = 300)

# for(i in 1:12) print(ggplot() +
#   geom_raster(data = as.data.frame(naive_predictions_cropped_df[,c(1,2,2+i)]), 
#               aes(x = x, y = y, fill = !!sym(colnames(as.data.frame(naive_predictions_cropped_df[2+i]))))) +
#     scale_fill_viridis_c(option = "D") +
#   geom_point(data = buffalo_CLR_year %>% filter(y == 1 & month == i), aes(x = x1, y = y1, colour = factor(id))) +
#   coord_equal() +
#   scale_x_continuous(limits = c(20000, 40000)) +
#   scale_y_continuous(limits = c(-1440000, -1430000)) +
#   theme_classic())


### RAW BCRW POINTS ###

ggplot() +
  geom_raster(data = points_df, aes(x = x, y = y, fill = naive_predictions)) +
  # geom_point(data = buffalo_CLR_year %>% filter(y == 1 & month == 1), aes(x = x1, y = y1)) +
  coord_equal() +
  # scale_x_continuous(limits = c(30000, 32000)) +
  # scale_y_continuous(limits = c(-1436000, -1434000)) +
  scale_fill_viridis_c(option = "D") +
  theme_classic()


### KDE BCRW POINTS ###

sim_pred <- ggplot() +
  geom_raster(data = kde_df, aes(x = x, y = y, fill = kde_estimate)) +
  # geom_path(data = buffalo_CLR_year %>% filter(y == 1 & month == 1 & id == 2154), 
  #           aes(x = x1 - xmin, y = y1 - ymin, colour = factor(id)), alpha = 0.5) +
  geom_point(data = buffalo_CLR_year %>% filter(y == 1 & month == 1), 
             aes(x = x1 - xmin, y = y1 - ymin), 
             size = 0.5, 
             colour = "red", alpha = 0.25) +
  coord_equal() +
  scale_x_continuous(limits = c(0, xmax - xmin)) +
  scale_y_continuous(limits = c(0, ymax - ymin)) +
  scale_fill_viridis_c("Simulated", option = "D") +
  theme_classic() +
  theme(legend.position = "bottom", legend.key.width = unit(1, "cm"))

# for(i in 1:12) print(ggplot() +
#   geom_raster(data = sim_data_kde_df, aes(x = x, y = y, fill = layer)) +
#   geom_path(data = buffalo_CLR_year %>% filter(y == 1 & month == i), aes(x = x1, y = y1, colour = factor(id))) +
#   coord_equal() +
#   scale_x_continuous(limits = c(30000, 32000)) +
#   scale_y_continuous(limits = c(-1436000, -1434000)) +
#   scale_fill_viridis_c(option = "D") +
#   theme_classic())

naive_pred + sim_pred

# use geom_point size = 0.5
# ggsave("outputs/plots/bcrw_simulations/naive_simulated_month1_20230223.png",
# width=150, height=90, units="mm", dpi = 300)
# # comment out geom_point size
# ggsave("outputs/plots/bcrw_simulations/naive_simulated_month1_pres_20230223.png",
# width=300, height=180, units="mm", dpi = 300, scale = 1)

```


# Boyce index

```{r}

ecospat.boyce2 <- function (fit, obs, nclass = 0, window.w = "default", res = 100, 
  PEplot = TRUE, rm.duplicate = TRUE, method = "spearman") 
{
  boycei <- function(interval, obs, fit) {
    pi <- sum(as.numeric(obs >= interval[1] & obs <= interval[2]))/length(obs)
    ei <- sum(as.numeric(fit >= interval[1] & fit <= interval[2]))/length(fit)
    return(round(pi/ei, 10))
  }
  if (inherits(fit, "RasterLayer")) {
    if (is.data.frame(obs) || is.matrix(obs)) {
      obs <- raster::extract(fit, obs)
    }
    fit <- getValues(fit)
    fit <- fit[!is.na(fit)]
    obs <- obs[!is.na(obs)]
  }
  mini <- min(fit, obs)
  maxi <- max(fit, obs)
  if (length(nclass) == 1) {
    if (nclass == 0) {
      if (window.w == "default") {
        window.w <- (max(fit) - min(fit))/10
      }
      vec.mov <- seq(from = mini, to = maxi - window.w, 
        by = (maxi - mini - window.w)/res)
      vec.mov[res + 1] <- vec.mov[res + 1] + 1
      interval <- cbind(vec.mov, vec.mov + window.w)
    }
    else {
      vec.mov <- seq(from = mini, to = maxi, by = (maxi - 
        mini)/nclass)
      interval <- cbind(vec.mov, c(vec.mov[-1], maxi))
    }
  }
  else {
    vec.mov <- c(mini, sort(nclass[!nclass > maxi | nclass < 
      mini]))
    interval <- cbind(vec.mov, c(vec.mov[-1], maxi))
  }
  f <- apply(interval, 1, boycei, obs, fit)
  to.keep <- which(f != "NaN")
  f <- f[to.keep]
  if (length(f) < 2) {
    b <- NA
  }
  else {
    r <- 1:length(f)
    if (rm.duplicate == TRUE) {
      r <- c(1:length(f))[f != c(f[-1], TRUE)]
    }
    b <- cor(f[r], vec.mov[to.keep][r], method = method)
  }
  HS <- apply(interval, 1, sum)/2
  if (length(nclass) == 1 & nclass == 0) {
    HS[length(HS)] <- HS[length(HS)] - 1
  }
  HS <- HS[to.keep]
  if (PEplot == TRUE) {
    plot(HS, f, xlab = "Habitat suitability", ylab = "Predicted/Expected ratio", 
      col = "grey", cex = 0.75)
    points(HS[r], f[r], pch = 19, cex = 0.75)
  }
  return(list(F.ratio = f, cor = round(b, 3), HS = HS))
}

```



```{r}

# ext(naive_predictions_cropped) <- ext(xmin, xmax, ymin, ymax)

# template_raster <- naive_predictions_cropped[[1]]
# plot(kde_with_extent, display = "image", col = viridis::viridis(20))
raster::values(template_raster) <- kde_with_extent$estimate
template_raster <- raster::raster(template_raster)
raster::plot(template_raster)
raster::plot(naive_predictions_cropped[[1]])

naive_cropped_raster <- raster::stack(naive_predictions_cropped)

```


setting up the buffalo observation data for the relevant month

```{r}

buffalo_obs <- buffalo_CLR_year %>% 
  filter(y == 1 & month == 1 & x1 > xmin & x1 < xmax & y1 > ymin & y1 < ymax) %>% 
  transmute(x = x1 - xmin, y = y1 - ymin)

```



```{r}

plot(naive_cropped_raster[[1]])

boyce_naive <- ecospat.boyce2(naive_cropped_raster[[1]], buffalo_obs,
                              # method = "spearman"
                              method = "pearson",
                              # method = "kendall"
                              )

boyce_naive

naive_BI_scaled <- data.frame("method" = rep("naive", length(boyce_naive[[1]])), 
           "F.ratio" = boyce_naive[[1]],
           "HS" = (boyce_naive[[3]] - min(boyce_naive[[3]])) / 
             (max(boyce_naive[[3]]) - min(boyce_naive[[3]])))


plot(template_raster)
# template_raster <- raster::raster(template_raster)

boyce_sim <- ecospat.boyce2(template_raster, buffalo_obs,
                            method = "pearson")

boyce_sim

sim_BI_scaled <- data.frame("method" = rep("naive", length(boyce_sim[[1]])), 
           "F.ratio" = boyce_sim[[1]],
           "HS" = (boyce_sim[[3]] - min(boyce_sim[[3]])) / 
             (max(boyce_sim[[3]]) - min(boyce_sim[[3]])))

```


```{r}

ggplot() +
  geom_point(data = naive_BI_scaled, aes(x = HS, y = F.ratio), colour = "skyblue") +
  geom_path(data = naive_BI_scaled, aes(x = HS, y = F.ratio), colour = "skyblue") +
  geom_point(data = sim_BI_scaled, aes(x = HS, y = F.ratio), colour = "orange") +
  geom_path(data = sim_BI_scaled, aes(x = HS, y = F.ratio), colour = "orange") +
  theme_classic()

ggsave(paste0("outputs/plots/bcrw_simulations/boyce_index_naive_sims_small_extent_month", month_n, "_20230228.png"),
width=150, height=90, units="mm", dpi = 300)
# comment out geom_point size
ggsave(paste0("outputs/plots/bcrw_simulations/boyce_index_naive_sims_small_extent_month", month_n, "_pres_20230228.png"),
width=300, height=180, units="mm", dpi = 300, scale = 1)

```



10,000 steps (1 individual)

```{r}

# kde_list_1indvs_rasters <- vector(mode = "list", length = 200)
# 
# for(i in 1:200){
#   temp_raster <- naive_predictions_cropped[[1]]
#   raster::values(temp_raster[[i]]) <- kde_list_1indvs[[i]]$estimate
#   names(temp_raster[[i]]) <- paste0("sim", i)
#   kde_list_1indvs_rasters[[i]] <- temp_raster
# }

```



```{r}

boyce_sim1indvs <- map(kde_raster_list_1indvs, ecospat.boyce2, buffalo_obs, PEplot = FALSE, method = "pearson")
boyce_sim2indvs <- map(kde_raster_list_1indvs, ecospat.boyce2, buffalo_obs, PEplot = FALSE, method = "pearson")
boyce_sim5indvs <- map(kde_raster_list_1indvs, ecospat.boyce2, buffalo_obs, PEplot = FALSE, method = "pearson")
boyce_sim10indvs <- map(kde_raster_list_10indvs, ecospat.boyce2, buffalo_obs, PEplot = FALSE, method = "pearson")
boyce_sim20indvs <- map(kde_raster_list_1indvs, ecospat.boyce2, buffalo_obs, PEplot = FALSE, method = "pearson")
boyce_sim25indvs <- map(kde_raster_list_1indvs, ecospat.boyce2, buffalo_obs, PEplot = FALSE, method = "pearson")
boyce_sim50indvs <- map(kde_raster_list_1indvs, ecospat.boyce2, buffalo_obs, PEplot = FALSE, method = "pearson")
boyce_sim100indvs <- map(kde_raster_list_1indvs, ecospat.boyce2, buffalo_obs, PEplot = FALSE, method = "pearson")

```



```{r}

correlation_df <- data.frame("indvs" = c(rep("cor_1indvs", 200), rep("cor_2indvs", 100), 
  rep("cor_5indvs", 40), rep("cor_10indvs", 20), 
  rep("cor_20indvs", 10), rep("cor_25indvs", 8), 
  rep("cor_50indvs", 4), rep("cor_100indvs", 2)
  # , "cor_200indvs"
  ),
  "cor" = c(map_dbl(1:200, function(i) boyce_sim1indvs[[i]]$cor),
            map_dbl(1:100, function(i) boyce_sim1indvs[[i]]$cor),
            map_dbl(1:40, function(i) boyce_sim1indvs[[i]]$cor),
            map_dbl(1:20, function(i) boyce_sim1indvs[[i]]$cor),
            map_dbl(1:10, function(i) boyce_sim1indvs[[i]]$cor),
            map_dbl(1:8, function(i) boyce_sim1indvs[[i]]$cor),
            map_dbl(1:4, function(i) boyce_sim1indvs[[i]]$cor),
            map_dbl(1:2, function(i) boyce_sim1indvs[[i]]$cor)
            # , 0.902
            ))

correlation_df$indvs <- factor(correlation_df$indvs, levels = c("cor_1indvs", "cor_2indvs", "cor_5indvs", "cor_10indvs", "cor_20indvs", "cor_25indvs", "cor_50indvs","cor_100indvs"
                                                                # ,"cor_200indvs"
                                                                ))

```



```{r}

# correlation_df %>% ggplot() +
#   geom_jitter(aes(x = indvs, y = cor), alpha = 0.25, width = 0.15) +
#   geom_hline(yintercept = 0.326, linetype = "dashed") +
#   scale_y_continuous("Pearson correlation") +
#   scale_x_discrete("Number of simulated locations", 
#                      labels = c(expression("1x10"^4), expression("2x10"^4), expression("5x10"^4),
#                                 expression("1x10"^5), expression("2x10"^5), expression("2.5x10"^5), 
#                                 expression("5x10"^5), expression("1x10"^6))) +
#   theme_bw()

correlation_df %>% ggplot() +
  geom_jitter(aes(x = indvs, y = cor), alpha = 0.25, width = 0.15) +
  geom_hline(yintercept = 0.326, linetype = "dashed") +
  scale_y_continuous("Pearson correlation coefficient") +
  scale_x_discrete("Ratio of simulated locations / landscape cells", 
                     labels = c(1,2,5,10,20,25,50,100)) +
  theme_bw()

# ggsave("outputs/plots/bcrw_simulations/pearson_correlation_increasing_sims_ratio_20230223.png",
# width=150, height=90, units="mm", dpi = 300)
# ggsave("outputs/plots/bcrw_simulations/pearson_correlation_increasing_sims_ratio_pres_20230223.png",
# width=300, height=180, units="mm", dpi = 300, scale = 1)

```



```{r}

# for(i in 1:12){
# boyce_naive[[i]] <- ecospat.boyce2(naive_pred_stack_raster[[i]], df_nest$data[[i]])
# }
# 
# boyce_naive_df <- bind_rows(boyce_naive)
# months <- rep(c(8:12, 1:7), each = 100)
# boyce_naive_df <- cbind(months, boyce_naive_df)

```


# For larger extent 

Month 1

```{r}

sim_data_filenames <- paste0("outputs/simulated trajectories/month1_lge_extent/", list.files(paste0("outputs/simulated trajectories/month1_lge_extent")))

sim_data_list <- map(sim_data_filenames, read_csv, show_col_types = FALSE)

sim_data_lge_ext_month1 <- do.call(rbind, sim_data_list) %>% dplyr::transmute(id, x = x_, y = y_)
index <- rep(1:length(sim_data_filenames), each = 1e3)
sim_data <- cbind(index, sim_data_lge_ext_month1)

```


Month 2

```{r}

sim_data_filenames <- paste0("outputs/simulated trajectories/month2_lge_extent/", list.files(paste0("outputs/simulated trajectories/month2_lge_extent")))

sim_data_list <- map(sim_data_filenames, read_csv, show_col_types = FALSE)

sim_data_lge_ext_month2 <- do.call(rbind, sim_data_list) %>% dplyr::transmute(id, x = x_, y = y_)
index <- rep(1:length(sim_data_filenames), each = 1e3)
sim_data <- cbind(index, sim_data_lge_ext_month2)

```


Month 3

```{r}

sim_data_filenames <- paste0("outputs/simulated trajectories/month3_lge_extent/", list.files(paste0("outputs/simulated trajectories/month3_lge_extent")))

sim_data_list <- map(sim_data_filenames, read_csv, show_col_types = FALSE)

sim_data_lge_ext_month3 <- do.call(rbind, sim_data_list) %>% dplyr::transmute(id, x = x_, y = y_)
index <- rep(1:length(sim_data_filenames), each = 1e3)
sim_data <- cbind(index, sim_data_lge_ext_month3)

```


```{r}

buffalo_CLR_year <- read_csv("outputs/buffalo_CLR_year_locations_20230220.csv")
attr(buffalo_CLR_year$t1, "tzone") <- "Australia/Queensland"
naive_predictions <- rast("mapping/pred_outputs/naive/naive_20230223/naive_stack_20230223.tif")

# larger extent
xmin <- 12500
xmax <- 45000
ymin <- -1445000
ymax <- -1427500

# 45000 - 12500 # 32500 m = 1300 cells
# -1427500 - -1445000 # 17500 m = 700 cells

crop_extent <- ext(xmin, xmax, ymin, ymax)
naive_predictions_cropped <- terra::crop(naive_predictions, crop_extent)

```


```{r}

month_n <- 1
buffalo_pres <- buffalo_CLR_year %>% filter(y == 1 & month == month_n)

terra::plot(naive_predictions_cropped[[month_n]])
points(buffalo_pres$x1, buffalo_pres$y1)

```


```{r}

template_raster <- naive_predictions_cropped[[month_n]]
ext(template_raster) <- c(xmin - xmin, xmax - xmin, ymin - ymin, ymax - ymin)
names(template_raster) <- "sim_predictions"
template_raster_df <- as.data.frame(raster(template_raster), xy = TRUE)
length(template_raster_df$sim_predictions) # should equal the number of cells - for some reason the terra rasters don't, which messes up the results 

sim_data_matrix <- as.matrix(sim_data %>% dplyr::select(x, y))

tic()
kde_lge_extent <- ks::kde(x = sim_data_matrix, 
                          # H = diag(c(2000, 2000)),
                          eval.points = template_raster_df[,1:2])
toc()

# kde_lge_extent_month1 <- kde_lge_extent
# kde_lge_extent <- kde_lge_extent_month1

# ks::Hpi.diag(sim_data_matrix)
# ks::Hlscv(sim_data_matrix)

```



```{r}

naive_predictions_month_n <- naive_predictions_cropped[[month_n]]
ext(naive_predictions_month_n) <- c(xmin - xmin, xmax - xmin, ymin - ymin, ymax - ymin)
naive_predictions_df <- as.data.frame(naive_predictions_month_n, xy = TRUE)

kde_df <- data.frame(kde_lge_extent$eval.points, "kde_estimate" = kde_lge_extent$estimate)

# points_df <- as.data.frame(points_norm, xy = TRUE)
# sim_data_kde_df <- as.data.frame(sim_data_kde_trim_norm, xy = TRUE)


### NAIVE ###

# naive_pred <- 
  
  ggplot() +
  geom_raster(data = naive_predictions_df, aes(x = x, y = y, fill = naive_predictions)) +
  geom_point(data = buffalo_pres, #  & hour %in% 12:17
             aes(x = x1 - xmin, y = y1 - ymin),  
             size = 0.5, 
             colour = "red", alpha = 0.25) +
  coord_equal() +
  scale_x_continuous(limits = c(0, xmax - xmin)) +
  scale_y_continuous(limits = c(0, ymax - ymin)) +
  # scale_x_continuous(limits = c(30000, 32000)) +
  # scale_y_continuous(limits = c(-1436000, -1434000)) +
  scale_fill_viridis_c("Naive", option = "D") +
  theme_classic() +
  theme(legend.position = "right", legend.key.width = unit(1, "cm"))
  
# ggsave(paste0("outputs/plots/bcrw_simulations/naive_lge_extent_preds_month", month_n, "_20230228.png"),
# width=150, height=90, units="mm", dpi = 300)
# # comment out geom_point size
# ggsave(paste0("outputs/plots/bcrw_simulations/naive_lge_extent_preds_month", month_n, "_pres_20230228.png"),
# width=300, height=180, units="mm", dpi = 300, scale = 1)


### KDE BCRW POINTS ###

# sim_pred <- 
  
  ggplot() +
  geom_raster(data = kde_df, aes(x = x, y = y, fill = kde_estimate)) +
  # geom_path(data = buffalo_CLR_year %>% filter(y == 1 & month == 1 & id == 2154), 
  #           aes(x = x1 - xmin, y = y1 - ymin, colour = factor(id)), alpha = 0.5) +
  geom_point(data = buffalo_pres, # buffalo_CLR_year %>% filter(y == 1 & month == 1)
             aes(x = x1 - xmin, y = y1 - ymin), 
             size = 0.5, 
             colour = "red", alpha = 0.25) +
  coord_equal() +
  scale_x_continuous(limits = c(0, xmax - xmin)) +
  scale_y_continuous(limits = c(0, ymax - ymin)) +
  scale_fill_viridis_c("Simulated", option = "D") +
  theme_classic() +
  theme(legend.position = "right", legend.key.width = unit(1, "cm"))
  
# ggsave(paste0("outputs/plots/bcrw_simulations/sim_lge_extent_preds_month", month_n, "_20230228.png"),
# width=150, height=90, units="mm", dpi = 300)
# # comment out geom_point size
# ggsave(paste0("outputs/plots/bcrw_simulations/sim_lge_extent_preds_month", month_n, "_pres_20230228.png"),
# width=300, height=180, units="mm", dpi = 300, scale = 1)

# naive_pred + sim_pred

```



```{r}

buffalo_obs <- buffalo_CLR_year %>% 
  filter(y == 1 & month == month_n & x1 > xmin & x1 < xmax & y1 > ymin & y1 < ymax) %>% 
  transmute(x = x1 - xmin, y = y1 - ymin)


# naive approach
naive_raster <- raster(naive_predictions_month_n)
plot(naive_raster)

boyce_naive_lge_extent <- ecospat.boyce2(naive_raster, buffalo_obs,
                              # method = "spearman"
                              method = "pearson",
                              # method = "kendall"
                              )

boyce_naive_lge_extent

naive_BI_scaled <- data.frame("method" = rep("naive", length(boyce_naive_lge_extent[[1]])), 
           "F.ratio" = boyce_naive_lge_extent[[1]],
           "HS" = (boyce_naive_lge_extent[[3]] - min(boyce_naive_lge_extent[[3]])) / 
             (max(boyce_naive_lge_extent[[3]]) - min(boyce_naive_lge_extent[[3]])))



# simulation approach
kde_raster <- raster(naive_predictions_month_n)

# length(kde_lge_extent$estimate)
# length(values(kde_raster))

raster::values(kde_raster) <- kde_lge_extent$estimate
names(kde_raster) <- "sim_predictions"
plot(kde_raster)

boyce_sim_lge_extent <- ecospat.boyce2(kde_raster, buffalo_obs,
                            method = "pearson")

boyce_sim_lge_extent

sim_BI_scaled <- data.frame("method" = rep("sim", length(boyce_sim_lge_extent[[1]])), 
           "F.ratio" = boyce_sim_lge_extent[[1]],
           "HS" = (boyce_sim_lge_extent[[3]] - min(boyce_sim_lge_extent[[3]])) / 
             (max(boyce_sim_lge_extent[[3]]) - min(boyce_sim_lge_extent[[3]])))

```



```{r}

ggplot() +
  geom_point(data = naive_BI_scaled, aes(x = HS, y = F.ratio), colour = "skyblue") +
  geom_path(data = naive_BI_scaled, aes(x = HS, y = F.ratio), colour = "skyblue") +
  geom_point(data = sim_BI_scaled, aes(x = HS, y = F.ratio), colour = "orange") +
  geom_path(data = sim_BI_scaled, aes(x = HS, y = F.ratio), colour = "orange") +
  theme_classic()

ggsave(paste0("outputs/plots/bcrw_simulations/boyce_index_naive_sims_lge_extent_month", month_n, "_20230228.png"),
width=150, height=90, units="mm", dpi = 300)
# comment out geom_point size
ggsave(paste0("outputs/plots/bcrw_simulations/boyce_index_naive_sims_lge_extent_month", month_n, "_pres_20230228.png"),
width=300, height=180, units="mm", dpi = 300, scale = 1)

```




