---
title: "MC-BM approx daily"
author: "Scott Forrest"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: inline
---

# Considering daily rhythmic behaviour in telemetry data improves buffalo management strategy

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Using Monte Carlo integration to approximate the redistribution kernel for the Barnett-Moorcroft approximation

Setting up the parameters

```{r}

library(terra)
library(tictoc)

# hourly_coefs_2harms_quads <- read_csv("outputs/daily_harmonic_coefs_df_with_movement_params_ndvi_canopy_herby_quads_20230524.csv")
hourly_coefs_2harms_quads <- read_csv("outputs/daily_2harmonic_coefs_df_ndvi_canopy_herby_quads_wet_20230524.csv")

hourly_coefs <- hourly_coefs_2harms_quads

```



```{r}

# normalised
# naive_ud <- terra::rast("mapping/naive_pred_stack_daily_2harms_ndvi2_canopy2_herby_wet_20230524.tif")
# unnormalised
naive_ud <- terra::rast("mapping/naive_pred_stack_unnorm_daily_2harms_ndvi2_canopy2_herby_wet_20230525.tif")
global(naive_ud[[i]], fun = "sum", na.rm = TRUE)

plot(naive_ud)
# y_ext <- terra::ext(resources[[1]])[4] - terra::ext(resources[[1]])[3]
# terra::ext(resources) <- c(0, 60000, 0, 57000)

# smaller 100 x 100 extent
xmin <- 30000
xmax <- 32500
ymin <- -1436000
ymax <- -1433500

# # smaller 100 x 100 extent
# xmin <- 30000
# xmax <- 32500
# ymin <- -1436000
# ymax <- -1433500
# 
# # larger extent
# xmin <- 17500
# xmax <- 40000
# ymin <- -1445000
# ymax <- -1427500

crop_extent <- ext(xmin, xmax, ymin, ymax)

naive_ud_cropped <- terra::crop(naive_ud, crop_extent)
ext(naive_ud_cropped) <- c(xmin - xmin, 
                            xmax - xmin, 
                            ymin - ymin, 
                            ymax - ymin)

# naive_ud_cropped_50m <- terra::aggregate(naive_ud_cropped)
# plot(naive_ud_cropped_50m[[1]])

global(naive_ud_cropped[[i]], fun = "sum", na.rm = TRUE)

i = 1
plot(naive_ud_cropped[[i]])
points(as.numeric(buffalo_CLR_year %>% 
                    filter(y == 1 & month %in% months_wet & hour == ifelse(i == 24, 0, i)) %>% 
                    dplyr::select(x1) %>% unlist()) - xmin, 
       as.numeric(buffalo_CLR_year %>% 
                    filter(y == 1 & month %in% months_wet & hour == ifelse(i == 24, 0, i)) %>% 
                    dplyr::select(y1) %>% unlist()) - ymin)

for(i in 1:24){
plot(naive_ud_cropped[[i]])
points(as.numeric(buffalo_CLR_year %>% 
                    filter(y == 1 & month %in% months_wet & hour == ifelse(i == 24, 0, i)) %>% 
                    dplyr::select(x1) %>% unlist()) - xmin, 
       as.numeric(buffalo_CLR_year %>% 
                    filter(y == 1 & month %in% months_wet & hour == ifelse(i == 24, 0, i)) %>% 
                    dplyr::select(y1) %>% unlist()) - ymin)
}

```

```{r}

naive_ud_cropped_df_list <- vector(mode = "list", length = 24)

# for(i in 1:24) naive_ud_cropped_df_list[[i]] <- as.data.frame(naive_ud_cropped[[i]], xy = TRUE)

naive_ud_cropped_df <- as.data.frame(naive_ud_cropped, xy = TRUE)

min(naive_ud_cropped_df[,3:26], na.rm = TRUE) # 0.00000001185235
max(naive_ud_cropped_df[,3:26], na.rm = TRUE) # 0.0000006519935


for(i in 1:24) {
  
plot <- ggplot() +
  geom_raster(data = naive_ud_cropped_df_list[[i]], aes(x = x, y = y, fill = mean)) +
  geom_point(data = buffalo_CLR_year_harmonics %>% 
               filter(y == 1 & month %in% months_wet & hour == ifelse(i == 24, 0, i)), 
             aes(x = x1, y = y1), colour = "red", size = 0.5) +
  coord_equal() +
  scale_x_continuous(limits = c(xmin, xmax )) + # - xmin
  scale_y_continuous(limits = c(ymin, ymax )) + # - ymin
  scale_fill_viridis_c("Habitat suitability", option = "D", direction = 1) +
  # , limits = c(0.00000001185235, 0.0000006519935)
  # scale_fill_distiller("Habitat suitability", palette = "Reds", direction = 1) +
  ggtitle(paste0("Hour ", i)) +
  theme_classic() +
  theme(legend.position = "right")

print(plot)

# ggsave(paste0("outputs/plots/hourly_preds/hourly_preds_", i, "_20230525.png"), width=150, height=90, units="mm", dpi = 300)

}

```




```{r}

n_proposals <- 100
grid_res <- terra::res(naive_ud_cropped)[1]
rows <- terra::nrow(naive_ud_cropped)
cols <- terra::ncol(naive_ud_cropped)

ud_template <- as.data.frame(ud_norm_list[[1]], xy = TRUE)
ud_template$mean <- NULL

ud_norm_list <- vector(mode = "list", length = 25)
ud_norm_list[[1]] <- naive_ud_cropped[[1]] # initialise the first UD to start with

tic()
for(i in 1:25) {
  
  i = 2

# von mises isn't considered as the turning angle is assumed to be uniform
# ta <- as.numeric(Rfast::rvonmises(n_proposals, m = pi, k = monthly_coefs$kappa[month_n]) - pi) 
# ta <- runif(n_proposals, min = -pi, max = pi)
# sl <- rgamma(n_proposals, shape = hourly_coefs$shape[1], scale = hourly_coefs$scale[1])

# hist(ta, breaks = 50)
# hist(sl, breaks = 50)

#######

ud_updated <- matrix(NA, nrow = rows, ncol = cols)

tic()
for(x_current in 1:cols) {
  for(y_current in 1:rows) {
    
    # x_current <- 2
    # y_current <- 99
    
    # tic()
    ta <- runif(n_proposals, min = -pi, max = pi)
    sl <- rgamma(n_proposals, shape = hourly_coefs$shape[i], scale = hourly_coefs$scale[i])
    # toc()
    
    # tic()
    matrix_row = rows - y_current + 1
    matrix_col = x_current
    # toc()
    
    # tic()
    x_proposal <- ((-(grid_res/2) + x_current * grid_res) + sl * sin(ta)) %% ext(naive_ud_cropped[[1]])[2] 
    y_proposal <- ((-(grid_res/2) + y_current * grid_res) + sl * cos(ta)) %% ext(naive_ud_cropped[[1]])[4]
    # toc()
    
    # tic()
    ud_updated[matrix_row, matrix_col] <-
    # ud_updated[x_current, y_current] <- 
      
      # as.numeric(terra::extract(ud_norm_list[[i]],
      #                           cbind((-(grid_res/2) + y_current * grid_res),
      #                                 (-(grid_res/2) + x_current * grid_res)))) *
      
      mean(terra::extract(naive_ud_cropped[[i + 1]], # take the z values from the next time point
                          cbind(x_proposal, y_proposal))[,1], na.rm = TRUE)
    # toc()
    
  }
}
toc()

#######

# exp(beta * Z(x))
# ud_norm_list[[i]] 
# global(ud_norm_list[[i]], fun = "sum")

# ud_template$value <- NULL
# ud_template_mat <- ud_template

# exp(beta * Z(z)) * psi(.) dz
# ud_updated/sum(ud_updated) # only makes 100 x 100 raster with resolution of 1
# ud_template$value <- as.vector(ud_updated/sum(ud_updated, na.rm = TRUE))
ud_template$value <- as.vector(ud_updated)
# plot(terra::rast(ud_template))
plot(terra::rev(rast(ud_template)))
# points(x_proposal, y_proposal)
# max(ud_template$value, na.rm = TRUE)

# exp(beta * Z(x)) * exp(beta * Z(z)) * psi(.) dz
u_x_unnorm <- ud_norm_list[[i]] * terra::rev(rast(ud_template))
plot(u_x_unnorm)
u_x <- u_x_unnorm / as.numeric(terra::global(u_x_unnorm, fun = "sum", na.rm = TRUE))
plot(u_x)
ud_norm_list[[i + 1]] <- u_x 

# ud_norm_list[[i + 1]] <- terra::rast(ud_updated/sum(ud_updated))  # normalise the UD and convert to a raster
# image(ud_updated)
# plot(naive_ud_cropped[[1]])
plot(ud_norm_list[[i + 1]])
# plot(terra::rast(ud_norm2))
points(as.numeric(buffalo_CLR_year_harmonics %>% 
                    filter(y == 1 & month %in% months_wet & hour == ifelse(i == 24, 0, i)) %>% 
                    dplyr::select(x1) %>% unlist()) - xmin, 
       as.numeric(buffalo_CLR_year_harmonics %>% 
                    filter(y == 1 & month %in% months_wet & hour == ifelse(i == 24, 0, i)) %>% 
                    dplyr::select(y1) %>% unlist())  - ymin)

}
toc()

# plot(ud_norm_list[[1]])
# plot(ud_norm_list[[2]])
# plot(ud_norm_list[[3]])
# plot(ud_norm_list[[4]])
# plot(ud_norm_list[[5]])

for(i in 1:25) {
  plot(ud_norm_list[[i]])
  points(as.numeric(buffalo_CLR_year_harmonics %>% 
                    filter(y == 1 & month %in% months_wet & hour == ifelse(i == 24, 0, i-1)) %>% 
                    dplyr::select(x1) %>% unlist()) - xmin, 
         as.numeric(buffalo_CLR_year_harmonics %>% 
                    filter(y == 1 & month %in% months_wet & hour == ifelse(i == 24, 0, i-1)) %>% 
                    dplyr::select(y1) %>% unlist())  - ymin)
}

terra::writeRaster(terra::rast(ud_norm_list), "mapping/MC-BM_approx_preds_20230525.tif")
save.image("MC-BM_approx_preds_20230524.RData")

```



```{r}


plot(x_proposal, y_proposal)

layer

layer[(x_val-1)*box_height+y_val]

x_pos <- (x[i - 1] + sl[steps == i] * sin(ta[steps == i])) %% ext(resc)[2] 
y_pos <- (y[i - 1] + sl[steps == i] * cos(ta[steps == i])) %% ext(resc)[4]

 p <- terra::extract(resources[[1]], cbind(x_proposal, y_proposal))[,1]
 


```


```{r}

# Get landscape as a matrix
layer<-as.matrix(read.table('random_field_100.inp',sep='\t',header=FALSE))

# Grab the beta coefficient for the landscape layer
# beta<-as.numeric(ssf1sim$coefficients[1])
beta<-2

# lambda<-(1/sl)-as.numeric(ssf1sim$coefficients[2])
lambda<-10

box_width = 100
box_height = 100

# Calculate y-values at each point in layer
y_vals<-rep(1:box_width,box_height)     

# Calculate x-values at each point in layer
x_vals<-c()
for(count in 1:box_height)
{
  x_vals<-c(x_vals,rep(count,box_width))  
}

# Calculate the predicted UD using the Barnett-Moorcroft method
ud<-c()

for(x_val in 1:box_height)
{
  for(y_val in 1:box_width)
  {
    
    # x_val = 1
    # y_val = 1
    
    # Value of the UD at this point, prior to normalising
    ud<-c(ud,exp(beta*layer[(x_val-1)*box_height+y_val])*sum(exp(-lambda*sqrt((x_vals-x_val)^2+(y_vals-y_val)^2))*exp(beta*layer)))
  }
}
ud<-ud/sum(ud)  # normalise the UD

# Plot the UD as a raster
library(raster)
xy<-cbind(x_vals,y_vals)
ras<-raster(ncols=box_width, nrows=box_height,xmn=0,xmx=box_width,ymn=0,ymx=box_height)
rud<-rasterize(xy,ras,ud)
plot(rud)

```



